add dbagent client
baishancloud/lua-acid pull request #100
Opened 2018-04-08 07:00 UTC by 13yu

2018-04-08 07:16 UTC, drmingdrmer requested changes

2018-04-08 07:16 UTC, drmingdrmer commented on lib/acid/dbagent/client.lua
> +    local timeout = opts.timeout or 1000
http的timeout貌似有3个: connect, send, recv. 这里是不是也要兼容下

2018-04-08 07:16 UTC, drmingdrmer commented on lib/acid/dbagent/client.lua
> +    local uri = opts.uri or string.format('/api/v1/%s/%s',
v1没有用变量

2018-04-08 07:16 UTC, drmingdrmer commented on lib/acid/dbagent/client.lua
> +    local ip = opts.ip or '127.0.0.1'
ip就不default了吧...还有port. 必须指定. 否则出错会很奇怪吧...

2018-04-08 07:16 UTC, drmingdrmer commented on lib/acid/dbagent/client.lua
> +    local ignore = opts.ignore or self.ignore
opts.ignore是false的话就出错了. 不要用or设置默认值吧.

2018-04-08 07:45 UTC, 13yu commented on lib/acid/dbagent/client.lua
> +    local timeout = opts.timeout or 1000
嗯，我加下

2018-04-08 07:46 UTC, 13yu commented on lib/acid/dbagent/client.lua
> +    local uri = opts.uri or string.format('/api/v1/%s/%s',
嗯

2018-04-08 07:46 UTC, 13yu commented on lib/acid/dbagent/client.lua
> +    local ip = opts.ip or '127.0.0.1'
好的

2018-04-08 07:46 UTC, 13yu commented on lib/acid/dbagent/client.lua
> +    local ignore = opts.ignore or self.ignore
我改下

2018-04-08 11:37 UTC, drmingdrmer approved these changes

2018-04-10 07:20 UTC, sejust approved these changes

2018-04-10 11:13 UTC, tongwei commented on lib/acid/dbagent/client.lua
> +        return nil, 'InvaliddbgentIps', string.format(
InvaliddbgentIps 大小写看着怪怪的

2018-04-10 11:13 UTC, tongwei commented on lib/acid/dbagent/client.lua
> +function _M.request_one_ip(self, dbagent_ip, port, timeout, dbagent_request)
这个要不把变量名去掉dbagent前缀，跟dbagent也没啥关系

2018-04-10 11:13 UTC, tongwei commented on lib/acid/dbagent/client.lua
> +    local timeout = self.timeout
timeout是单次的吗，不是包含重试的吗

2018-04-10 11:21 UTC, 13yu commented on lib/acid/dbagent/client.lua
> +        return nil, 'InvaliddbgentIps', string.format(
嗯。我改下

2018-04-10 11:22 UTC, 13yu commented on lib/acid/dbagent/client.lua
> +function _M.request_one_ip(self, dbagent_ip, port, timeout, dbagent_request)
好的

2018-04-10 11:22 UTC, 13yu commented on lib/acid/dbagent/client.lua
> +    local timeout = self.timeout
是单次的

2018-04-11 03:23 UTC, tongwei approved these changes

2018-04-17 08:37 UTC, merged