adjust the judge default value of withzone
baishancloud/lua-acid pull request #14
Opened 2017-04-25 03:28 UTC by liu-s-yuan

2017-04-25 03:37 UTC, drmingdrmer reviewed
增加些边界测试.

2017-04-25 03:37 UTC, drmingdrmer commented on lib/acid/time.lua
> +            return nil, 'FormatError', dt..' date dormat error'
`..`两侧加空格

2017-04-25 03:37 UTC, drmingdrmer commented on lib/test_time.lua
> +    t:eq( sec, tosec(1492398063001), msg .. 1492398063001 )
测试需要多考虑几个边界条件

2017-04-25 03:37 UTC, drmingdrmer commented on lib/test_time.lua
> +    t:eq( err, 'ArgumentError', err_msg )
这个case为什么会出错?

2017-04-25 03:37 UTC, drmingdrmer commented on lib/test_time.lua
>      local tosec = time.to_sec
to_sec = time.to_sec

用tosec这种不规则的替换对代码不健康.

2017-04-27 09:25 UTC, pengsven commented on lib/acid/time.lua
> +            'timestamp cannot tonumber or ts < 0, or ts is scientific notation'
errmsg 描述和实现不一样

2017-04-27 13:48 UTC, drmingdrmer requested changes

2017-04-27 13:48 UTC, drmingdrmer commented on lib/acid/time.lua
>      end
直接对number进行处理, 不需要转string

2017-04-28 15:03 UTC, drmingdrmer requested changes

2017-04-28 15:03 UTC, drmingdrmer commented on lib/acid/time.lua
> +            ts = ts:sub(1, -3 - 1)
-1 可以不用

2017-04-28 15:03 UTC, drmingdrmer commented on lib/acid/time.lua
> +        end
这步判断有什么意义?

2017-04-28 15:03 UTC, drmingdrmer commented on lib/acid/time.lua
> +        end
10000000000 这个值是什么含义,为什么是10000000000?

2017-04-28 15:03 UTC, drmingdrmer commented on lib/acid/time.lua
> +    else
对数字类型的情况处理太复杂了. 想个简单的方法.

2017-04-28 15:03 UTC, drmingdrmer commented on lib/test_time.lua
> +        {
测试不完整. 考虑输入所有可能的情况, 去设计测试.

2017-07-14 12:10 UTC, pengsven approved these changes

2017-07-14 12:10 UTC, pengsven commented on lib/acid/time.lua
> +            'timestamp cannot be converted to number or less than 0, ts:' .. ts
errmes中的 ts用tostring(ts)下，再连接字符串

2017-07-14 17:15 UTC, drmingdrmer commented on lib/acid/time.lua
> +            'timestamp cannot be converted to number or less than 0, ts:' .. ts
这里缺少测试吧?

2017-07-14 17:21 UTC, drmingdrmer requested changes

2017-07-14 17:21 UTC, drmingdrmer commented on lib/test_time.lua
> +            out=nil
上面这些case看不出来为什么out是nil, 把代码写成能看出设计思路的形式.

2017-07-17 05:28 UTC, drmingdrmer approved these changes

2017-07-17 05:28 UTC, drmingdrmer commented on lib/test_time.lua
> +            errmes='invalid time length, not 10, 13, 16 or 19, ts:12345'
```
'1499850242':sub(1, -2)
'1499850242' .. '1'
```

2017-07-17 05:28 UTC, drmingdrmer commented on lib/test_time.lua
> +            args='1499850242000',
args='1499850242' .. '000',

2017-07-17 05:28 UTC, drmingdrmer commented on lib/test_time.lua
> +            errmes='timestamp cannot be converted to number or less than 0, ts:-1499850242'
message缩写统一用msg吧.

2017-07-17 05:28 UTC, drmingdrmer commented on lib/test_time.lua
> +            res=nil,
测试case里的结果的变量名建议用expected

2017-07-17 05:28 UTC, drmingdrmer commented on lib/test_time.lua
> +        if err ~= nil then
case里面的输入输出可以考虑用dd()输出1下,需要调试的时候方便1点.

2017-07-17 05:36 UTC, liu-s-yuan commented on lib/acid/time.lua
> +            'timestamp cannot be converted to number or less than 0, ts:' .. ts
:+1:

2017-07-17 05:37 UTC, liu-s-yuan commented on lib/test_time.lua
> +            out=nil
:+1:

2017-07-17 05:39 UTC, liu-s-yuan commented on lib/test_time.lua
> +            args='1499850242000',
:+1:

2017-07-17 05:39 UTC, liu-s-yuan commented on lib/test_time.lua
> +            errmes='invalid time length, not 10, 13, 16 or 19, ts:12345'
:heart:

2017-07-17 05:39 UTC, liu-s-yuan commented on lib/test_time.lua
> +            res=nil,
:heart:

2017-07-17 05:39 UTC, liu-s-yuan commented on lib/test_time.lua
> +            errmes='timestamp cannot be converted to number or less than 0, ts:-1499850242'
:+1:

2017-07-17 05:40 UTC, liu-s-yuan commented on lib/test_time.lua
> +        if err ~= nil then
:+1:

2017-07-24 13:43 UTC, drmingdrmer requested changes

2017-07-24 13:43 UTC, drmingdrmer commented on t/test_all.t
> +                "test_time",
这个已经过期了. 自己的分支记得及时rebase到最新的master.

2017-07-24 13:43 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return nil, 'FormatError', 'type: ' .. type(dt) .. ' date format error'
这种错误可以用assert. 基本可以确定是代码编写问题.错误处理只处理非预期的问题, 像网络超时这种.

2017-07-24 13:43 UTC, drmingdrmer commented on lib/acid/time.lua
> +            return nil, 'FormatError', dt .. ' date dormat error'
dormat 写错了..

2017-07-24 13:43 UTC, drmingdrmer commented on lib/acid/time.lua
> +function _M.format_ngxerrorlog(ts, withzone)
给个_M.format的接口吧, 简单点.每个都加后缀不太容易使用和扩展.

```
format(ts,fmt,withzone)
```
酱.

2017-07-25 02:00 UTC, liu-s-yuan commented on t/test_all.t
> +                "test_time",
嗷嗷～

2017-07-25 10:59 UTC, drmingdrmer requested changes

2017-07-25 10:59 UTC, drmingdrmer commented on lib/acid/time.lua
> +            return nil, 'FormatError', dt .. ' date format error'
错误信息没有说明 哪里出错. 所有错误信息要明确到底哪里出错. 否则调试程序时错误信息没有任何帮助.

2017-07-25 10:59 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return nil, 'ArgumentError', 'timestamp cannot tonumber'
'timestamp cannot tonumber' 语法不正确啊..

2017-07-25 10:59 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return _parse( dt, 'ngxerrorlog', withzone )
上面这坨可以简化. 拒绝没有经过仔细斟酌的无脑代码.

2017-07-25 10:59 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return nil, 'FmtkeyError', 'date cannot be formated into a timestamp'
把vim的spell check打开检查下错误的单词.

2017-07-25 10:59 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return _format( ts, 'ngxerrorlog', withzone )
冗余代码太多

2017-07-25 10:59 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return nil, 'FmtkeyError', 'timestamp cannot be converted'
error code里用完整单词.

2017-07-25 10:59 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return nil, 'FmtkeyError', 'timestamp cannot be converted'
注意大小写. 每个提交的字母都要规范

2017-07-25 10:59 UTC, drmingdrmer commented on lib/test_time.lua
> +    t:eq( utc_time, local_time+timezone, 'timezone is wrong, timezone:' .. timezone )
`+`两侧没有留空格.

2017-07-25 10:59 UTC, drmingdrmer commented on lib/test_time.lua
> +            err_msg='timestamp cannot be scientific notation or decimal, ts:1.499850242e+15'
err_msg一般不用测试. 因为变化太多了. 只测试err code

2017-07-25 10:59 UTC, drmingdrmer commented on lib/test_time.lua
> +        local ts, err, err_msg = time.to_sec(case.args)
参考下最新的strutil的测试.可以减少不少重复的代码.

2017-07-25 11:07 UTC, liu-s-yuan commented on lib/acid/time.lua
> +        return nil, 'ArgumentError', 'timestamp cannot tonumber'
我去改改～

2017-07-25 11:08 UTC, liu-s-yuan commented on lib/acid/time.lua
> +        return _parse( dt, 'ngxerrorlog', withzone )
嗷嗷～ :heart:

2017-07-25 11:10 UTC, liu-s-yuan commented on lib/acid/time.lua
> +        return nil, 'FmtkeyError', 'timestamp cannot be converted'
嗷嗷～好的

2017-07-25 11:11 UTC, liu-s-yuan commented on lib/test_time.lua
> +        local ts, err, err_msg = time.to_sec(case.args)
好，我去看看～

2017-07-27 06:20 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return _format( ts, fmtkey, default_false(withzone) )
这部分对应关系,用个全局table来map他们的行为.

2017-07-27 06:20 UTC, drmingdrmer commented on lib/test_time.lua
> +        {-1499850242,                             nil,        'ArgumentError' },
测试下边界,-1 0 这些值.

2017-07-27 06:20 UTC, drmingdrmer commented on lib/test_time.lua
> +    for args, expected, err_code, desc in t:case_iter(3, {
args这个变量名不太合适.

2017-07-27 06:27 UTC, pengsven approved these changes

2017-07-27 06:30 UTC, liu-s-yuan commented on lib/test_time.lua
> +        {-1499850242,                             nil,        'ArgumentError' },
嗷嗷～ :heart:

2017-07-28 04:16 UTC, drmingdrmer approved these changes

2017-07-28 13:47 UTC, merged