为acid
baishancloud/lua-acid pull request #36
Opened 2017-08-03 08:23 UTC by liu-s-yuan

* add doc for time.parse()

* add doc for time.format()

* add doc for time.timezone

* add doc for time.to_sec()

2017-08-03 08:30 UTC, drmingdrmer requested changes
文档仔细考虑下别人怎么看最清楚.

2017-08-03 08:30 UTC, drmingdrmer commented on doc/acid/time.md
> +    -   and it can not be decimal or less than 0.
不用2级列表了吧?
`it can not be decimal or less than 0.` 不能是10进制的?

2017-08-03 08:30 UTC, drmingdrmer commented on doc/acid/time.md
> +number.
integer number 准确点.

2017-08-03 08:30 UTC, drmingdrmer commented on doc/acid/time.md
> +    specify time string format.
specifies

2017-08-03 08:30 UTC, drmingdrmer commented on doc/acid/time.md
> +    is a Boolean value to determine if time has timezone.
说明下default value是啥

2017-08-03 08:30 UTC, drmingdrmer commented on doc/acid/time.md
> +    'nginxerrorlog ': '(%d+)%/(%d+)%/(%d+)% (%d+):(%d+):(%d+)',
这种东西给用户看有什么用?

2017-08-03 08:33 UTC, liu-s-yuan commented on doc/acid/time.md
> +    is a Boolean value to determine if time has timezone.
这里是和parse函数一样的，所以我写了See also time.parse。我去把它写出来

2017-08-03 08:33 UTC, liu-s-yuan commented on doc/acid/time.md
> +    specify time string format.
嗷嗷～

2017-08-03 08:33 UTC, liu-s-yuan commented on doc/acid/time.md
> +    'nginxerrorlog ': '(%d+)%/(%d+)%/(%d+)% (%d+):(%d+):(%d+)',
我去改改

2017-08-03 08:34 UTC, liu-s-yuan commented on doc/acid/time.md
> +number.
嗷嗷，明白了

2017-08-03 08:34 UTC, liu-s-yuan commented on doc/acid/time.md
> +    -   and it can not be decimal or less than 0.
‘decimal’是小数

2017-08-03 08:34 UTC, liu-s-yuan commented on doc/acid/time.md
> +    -   and it can not be decimal or less than 0.
嗷嗷，我去改一下耳机列表

2017-08-03 09:41 UTC, drmingdrmer commented on doc/acid/time.md
> +    -   and it can not be decimal or less than 0.
小数..用float吧

2017-08-03 10:56 UTC, liu-s-yuan commented on doc/acid/time.md
> +    -   and it can not be decimal or less than 0.
嗷嗷，好～

2017-08-04 07:31 UTC, pengsven requested changes

2017-08-04 07:31 UTC, pengsven commented on doc/acid/time.md
> +
这里为啥要用两个空行？和上下文没有关联的代码用一个空行隔开。

2017-08-04 07:31 UTC, pengsven commented on doc/acid/time.md
> +
和上下文相关的不要空白行

2017-08-04 07:35 UTC, liu-s-yuan commented on doc/acid/time.md
> +
我是想函数前后用两个空行隔开比较清楚，那我去改下

2017-08-04 07:35 UTC, liu-s-yuan commented on doc/acid/time.md
> +
嗷嗷～

2017-08-04 08:08 UTC, pengsven approved these changes

2017-08-09 02:58 UTC, drmingdrmer approved these changes

2017-08-09 03:09 UTC, closed without merging