add doc for tableutil
baishancloud/lua-acid pull request #38
Opened 2017-08-19 03:50 UTC by wenbobuaa

补了`tableutil`的文档。

2017-08-19 05:58 UTC, drmingdrmer requested changes

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +**syntax**:
标题上下要留空行..否则有时会有语法问题..

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +number of keys in `tbl`.
return 和下面的描述之间不留空行. 渲染之后就是1句完整的句子了.

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Copy digital index values in `tbl` until the first nil value. do deep copy if `deep` is `true`, shallow copy else.
建议每个句子`.` 分隔的, 都换一行.md源文件保持单行不要太长.

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Copy digital index values in `tbl` until the first nil value. do deep copy if `deep` is `true`, shallow copy else.
注意句子首字母大写..
deep是可选的, 需要描述下default是啥.

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Copy digital index values in `tbl` until the first nil value. do deep copy if `deep` is `true`, shallow copy else.
By default `deep` is `false`. blabla..

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +
加空行:
```
**arguments**:

-   `tbl`: is a table.

-   `deep`: is a boolean, deep copy if `deep` is true, shallow copy else.
```

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +`tableutil.dup(tbl, deep, ref_table)`
ref_table是内部使用的.实际上不应该由用户来指定这个参数. 文档上去掉吧. 后面再把代码规范下不暴露这个参数.

代码你都看了吗?

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Get a table whose keys are shared by all tables in `tables`. If `val` is not `nil`, every values of these keys are `val`, else are the values of these keys in first table of `tables`.
单行太长. 80或120宽 配置下vim的textwidth

2017-08-19 05:58 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +-   `val`: a value assigned to shared keys.
`val`: is a value assigned to shared keys.
加个is,让这1段读起来是1句完整的句子.

2017-08-19 06:01 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +-   `val`: a value assigned to shared keys.
好，我把上面这些都再改一下。

2017-08-19 06:03 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +`tableutil.dup(tbl, deep, ref_table)`
嗯 代码都看过了。在这写了让 ref_table 参数为空，直接去掉吧。

2017-08-21 03:46 UTC, drmingdrmer requested changes

2017-08-21 03:46 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Value is a primitive value, and key_path is a series keys access to the value.
给个例子吧.光看文档看不懂.

2017-08-21 03:46 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Copy digital index values in `tbl` until the first nil value found.
digital指单个数字.这里说 copy all int number indexed key-value in `tbl` blabla..咋样?

2017-08-21 03:46 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +We expained what **contain** means at the begining.
不是at beginning..直接See `tableutil.contains`吧. beginning少了个n. vim里:set spell可以检查语法.

2017-08-21 03:46 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +    is a key_path.
is a key_path这种描述读者还是不知道它到底是啥. 从读者角度重新review下文档.看是否做为小白能看懂. 必要是给例子是最直接简单的.

2017-08-21 03:46 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +the value found, or nil, error and error message.
这句话结构有点问题..

2017-08-21 03:46 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +`nil` is in `tbl`.
`nil` is in `tbl`.

这啥意思?

2017-08-21 03:46 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +`tableutil.update(tbl, src, opts, ref_table)`
ref_table不要了吧? 需要吗?

2017-08-21 03:49 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +Value is a primitive value, and key_path is a series keys access to the value.
嗯 好，我在有的地方再加一些使用示例吧

2017-08-21 03:49 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +Copy digital index values in `tbl` until the first nil value found.
好 改一下

2017-08-21 03:50 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +We expained what **contain** means at the begining.
嗯 我改一下

2017-08-21 03:51 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +`nil` is in `tbl`.
想说， `value` 是 `nil` 的时候会返回 `true`..

2017-08-21 03:51 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +`tableutil.update(tbl, src, opts, ref_table)`
嗯 这里不要了。我再看看 修改下

2017-08-21 03:53 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +`nil` is in `tbl`.
```
`nil` is always in `tbl`
```
酱?

2017-08-21 03:54 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +`nil` is in `tbl`.
嗯 对 是这样的意思。

2017-08-21 09:35 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +Return `tbl` if either of `tbl` and `tvals` is not a table.
@drmingdrmer 源代码里，这里的判断逻辑是：
```
if type(tbl) ~= 'table' or tvals ~= nil then
    return tbl
end
```
但是后面直接 `ipairs(tvals)`， 看起来如果 tvals 不是 table 会出问题。

2017-08-21 09:38 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +
@drmingdrmer 源代码里，math.random() 没有设置种子，这样每次调用都会从同样的位置开始切片，在这不要紧吗？

2017-08-23 08:42 UTC, drmingdrmer requested changes

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +
这里不设置吧, 应该是它调用者的责任去设置.

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Return `tbl` if either of `tbl` and `tvals` is not a table.
恩.这里需要加个测试和检查.

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +local deep_iter = tableutil.deep_iter
例子尽可能简单..这些优化不用了..能说明用法就好.require也不用.. deep_iter可以直接用在for循环里. 参考测试代码

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +    is a table.
a和b都可以是原始类型.

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +`tbl`.
句子说完整比较好.. `**return**:  the first argument tbl itself`

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Get the value **key path** `keys` access to in table `tbl` if found.
get the value by **key path** `keys` in table `tbl`

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +print(_get(tbl, keys))
例子要尽量简单.不求完整.

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +```
code block 的3个反引号上面要留空行.

2017-08-23 08:42 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +If `value` is int number indexed, **remove** means to remove from table.
If `value` is int number indexed, **remove** means to remove from table.

这句话没太说明白. 你要表达的是 if `value` is indexed by an integer(a list style element), it is removed and all following elements are moved left by one position. If `value` is indexed by a string or other type key(a dictionary style element), just set the key to `nil`.

2017-08-23 08:48 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +local deep_iter = tableutil.deep_iter
好， 我把例子里这些简化一下

2017-08-23 08:49 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +If `value` is int number indexed, **remove** means to remove from table.
嗯 确实没有，照你的改一下

2017-08-23 10:55 UTC, drmingdrmer requested changes

2017-08-23 10:55 UTC, drmingdrmer commented on lib/acid/tableutil.lua
> +    if type(tbl) ~= 'table' or type(tvals) ~= 'table' then
应该是只接受nil和table. 其他应该报错不应该直接返回.

2017-08-23 10:55 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +    is list table filled with tables.
is a list of tables

2017-08-23 10:55 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +    if k ~= nil and v ~= nil then
这里判断nil是什么意思?

2017-08-23 10:55 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +Get a table whose keys are those apeared at least once in one of the tables
appeared vim里:set spell 把语法检查打开.

2017-08-23 10:55 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +If `value` is int number indexed, **remove it from table and all
少了半个`**`

这次修改的略仓促啊.

2017-08-23 11:05 UTC, wenbobuaa commented on doc/acid/tableutil.md
> +    if k ~= nil and v ~= nil then
这里是之前的误写。。看不懂
我改下

2017-08-23 11:05 UTC, wenbobuaa commented on lib/acid/tableutil.lua
> +    if type(tbl) ~= 'table' or type(tvals) ~= 'table' then
好，我再改下

2017-08-23 11:48 UTC, drmingdrmer requested changes

2017-08-23 11:48 UTC, drmingdrmer commented on lib/test_tableutil.lua
>      for ii, c in ipairs( cases ) do
这里用的还是旧的测试?可以用case_iter那个函数.方便点..你参考下其他几个测试

2017-08-23 11:48 UTC, drmingdrmer commented on lib/test_tableutil.lua
> +        local rst, err= tableutil.extends(inp, inp2)
一般返回的错误只处理非人为错误.像网络错误或用户输入错误. 如果这里出错,肯定是代码逻辑问题.不用返回,extends这里应该直接抛出异常中断程序,用error()或者让代码自己出错.

2017-08-23 11:52 UTC, wenbobuaa commented on lib/test_tableutil.lua
> +        local rst, err= tableutil.extends(inp, inp2)
这样的话，好像原来的做法就是让代码自己出错。那就不用再修改了

2017-08-23 16:38 UTC, drmingdrmer approved these changes

2017-08-24 02:08 UTC, merged