add timestamp conversion #46-acid/time
baishancloud/lua-acid pull request #47
Opened 2017-08-28 02:29 UTC by wenbobuaa

添加将时间戳转换为毫秒，微妙和纳秒的函数。

2017-08-28 02:54 UTC, liu-s-yuan commented on lib/acid/time.lua
> +        ts = ts
@wenbobuaa ，这里的 else ts=ts 就不需要了吧

2017-08-28 02:55 UTC, liu-s-yuan approved these changes

2017-08-28 03:00 UTC, wenbobuaa commented on lib/acid/time.lua
> +        ts = ts
嗯 是。这样想，好像所有的 if-else 都不需要，我改一下。

2017-08-28 03:10 UTC, drmingdrmer requested changes

2017-08-28 03:10 UTC, drmingdrmer commented on lib/acid/time.lua
> +local function is_timestamp(ts)
这段逻辑跟之前的代码有重复. 重构整理下. 尽量不要引入重复逻辑.

2017-08-28 03:10 UTC, drmingdrmer commented on lib/acid/time.lua
> +function _M.to_ms(ts)
一般ts都是数字,如果是返回字符串的话最好函数名上能明确看出来.

2017-08-28 03:10 UTC, drmingdrmer commented on lib/test_time.lua
> +        {'abcdefghij',          nil, 'ArgumentError'},
case们左对齐吧..

2017-08-28 03:10 UTC, drmingdrmer commented on lib/acid/time.lua
> +    end
这里不判断直接split逻辑简单点吧?

2017-08-28 03:10 UTC, drmingdrmer commented on lib/acid/time.lua
> +    if tableutil.has({10, 13, 16, 19},  # ts) then
或者不用table直接if判断, 或者用个字典风格的table直接取数字的key来判断.

每次都重建1个table影响效率,需要的话设置为module里的全局变量.

has()是线性查找的效率.

2017-08-28 03:10 UTC, drmingdrmer commented on lib/acid/time.lua
> +    ts, err, errmsg = is_timestamp(ts)
is_timestamp 这种结构的名字`is_xxx` 一般都只返回bool类型的结果. 这里要返回转换后的ts的话不应该用is_xx的名字.

2017-08-28 03:10 UTC, drmingdrmer commented on lib/test_time.lua
> +        dd(ts, expected)
这里dd()的应该是rst吧?答应expected有啥用啊. case_iter里已经打印了.

2017-08-28 03:12 UTC, wenbobuaa commented on lib/acid/time.lua
> +local function is_timestamp(ts)
好，我重构下。

2017-08-28 06:26 UTC, drmingdrmer requested changes

2017-08-28 06:26 UTC, drmingdrmer commented on lib/acid/time.lua
> +    ts = string.sub(ts..'000000000', 1, 19)
strutil 有这2个函数
```
function _M.ljust(str, n, ch)
    return str .. string.rep(ch or ' ', n - string.len(str))
end


function _M.rjust(str, n, ch)
    return string.rep(ch or ' ', n - string.len(str)) .. str
end
```

2017-08-28 06:26 UTC, drmingdrmer commented on lib/acid/time.lua
>          return nil, 'ArgumentError',
建议非法数字和负数的错误分开处理, 返回不同的, 明确的错误码.

2017-08-28 06:26 UTC, drmingdrmer commented on lib/acid/time.lua
>          return nil, 'ArgumentError',
错误码具体点.

2017-08-28 06:26 UTC, drmingdrmer commented on lib/acid/time.lua
> +    ts = ts[1]
用1个变量重复使用,而且是不同的类型不太好. 整个过程中变量的含义变了但是名字都是1个.

逻辑上不同含义的变量就用不同的名字. 混用也容易引起错误.

2017-08-28 06:26 UTC, drmingdrmer commented on lib/acid/time.lua
> +}
这个表可以做的更有用1点:
```
local ts_len_to_unit = {
[10] = 'sec',
[13] = 'ms',
...
```

2017-08-28 06:26 UTC, drmingdrmer commented on lib/test_time.lua
> +        {'abcdefghij',              nil,       'ArgumentError'},
错误测试随意给个输入意义不大, 主要关注边界. 这个测试的目标应该是:
bool类型,函数类型,空串, 单字母, 多字母等等输入情况下的结果.

2017-08-28 06:32 UTC, wenbobuaa commented on lib/test_time.lua
> +        {'abcdefghij',              nil,       'ArgumentError'},
好，测试我重写下

2017-08-28 07:00 UTC, wenbobuaa commented on lib/acid/time.lua
> +    ts = string.sub(ts..'000000000', 1, 19)
这里为了不判断ts的位数，直接扩展了位数再截取需要的部分。如果用这两个函数还要在扩展之后判断为数再截取。会更慢

2017-08-28 07:26 UTC, drmingdrmer commented on lib/acid/time.lua
> +    ts = string.sub(ts..'000000000', 1, 19)
好

2017-08-28 09:00 UTC, drmingdrmer requested changes

2017-08-28 09:00 UTC, drmingdrmer commented on lib/test_time.lua
> +        {1503831195123456789,       nil,                   'NumberError'     },
错误码不一定一定要带xxxError, 这种情况下, NotNumber, InvalidLength, NotPositiveNumber, 这种错误码更能说明问题.

2017-08-28 09:00 UTC, drmingdrmer commented on lib/acid/time.lua
> +    [10]='sec',
这块我在想是用s好 还是用sec好...

2017-08-28 09:00 UTC, drmingdrmer commented on lib/acid/time.lua
> +        return nil, 'NumberError',
ScientificNotationNotAllowed 酱?

2017-08-28 09:04 UTC, wenbobuaa commented on lib/acid/time.lua
> +        return nil, 'NumberError',
嗯嗯 改一下

2017-08-28 09:04 UTC, wenbobuaa commented on lib/test_time.lua
> +        {1503831195123456789,       nil,                   'NumberError'     },
嗷嗷 那我把这些改一改

2017-08-28 09:04 UTC, wenbobuaa commented on lib/acid/time.lua
> +    [10]='sec',
要不用 s  吧，和其他几个一样取他们的单位

2017-08-30 02:29 UTC, drmingdrmer requested changes

2017-08-30 02:29 UTC, drmingdrmer commented on lib/test_time.lua
> +        {-1503831195,               nil,                   'NegativeNumber'               },
NegativeNumber  这个错误不太明确, 最好用否定语气来描述错误. NotPositiveNumber或就NotPositive
比如对于传入function类型, 返回NotNumber这个错误就比较明确. 但如果换成Function就不清楚. 不知道是应该是个Function还是不应该是个Function.

错误里明确地否定1个东西比较好.

2017-08-30 02:29 UTC, drmingdrmer commented on lib/acid/time.lua
> +    return string.sub(origin_ts..'000000000', 1, 19)
to_str_xx这3个函数可以合并下吧? 除了补齐的逻辑不一样其他都1样.

给个最简练的实现.

2017-08-30 02:32 UTC, wenbobuaa commented on lib/acid/time.lua
> +    return string.sub(origin_ts..'000000000', 1, 19)
好，我重写下

2017-08-30 02:32 UTC, wenbobuaa commented on lib/test_time.lua
> +        {-1503831195,               nil,                   'NegativeNumber'               },
我改一下

2017-09-01 06:39 UTC, drmingdrmer approved these changes

2017-09-01 06:39 UTC, drmingdrmer commented on doc/acid/time.md
> +**return**
`**return**:` 后面加个冒号~

snipmate, ultisnip 选个vim的snippet 引擎, 可以减少很多重复的代码输入

2017-09-01 06:39 UTC, drmingdrmer commented on lib/acid/time.lua
> +    local ts_s, err, errmsg = ts_conversion(ts, 10)
这里命名上直接用sec替代ts_s更明白点好像?

2017-09-01 07:10 UTC, closed without merging