add some functions on the operation of time
baishancloud/lua-acid pull request #54
Opened 2017-09-11 03:40 UTC by liu-s-yuan

* add time.get_time() to get seconds, miliseconds and microseconds

* add time.ts() to get timestamp in second

* add time.ms() to get timestamp in milisecond

* add time.us() to get timestamp in microsecond

2017-09-11 03:52 UTC, drmingdrmer requested changes

2017-09-11 03:52 UTC, drmingdrmer commented on doc/acid/time.md
> +For example: `1504925787    971   971777`
例子里给出完整的返回格式. 这种含糊的空格分隔的示意文字会误导用户

2017-09-11 03:52 UTC, drmingdrmer commented on doc/acid/time.md
> +miliseconds and microseconds.
为啥同事返回milli 和micro?

`milli` 不是 `mili` 你有英文语法检查工具吗? 没有赶快整1个.

review的代码中别带上这种机器能检查出来的低级错误.

2017-09-11 03:53 UTC, liu-s-yuan commented on doc/acid/time.md
> +For example: `1504925787    971   971777`
嗷嗷，我去改一下

2017-09-11 06:42 UTC, wenbobuaa commented on doc/acid/time.md
> +  - [time.us](#timeus)
可以调整1下 按字母顺序排列哈

2017-09-11 06:42 UTC, wenbobuaa commented on lib/acid/time.lua
> +
看起来 get_time 可以作为一个内部函数不暴露出来。
其他三个函数 叫做 get_sec, get_ms, get_str_us
这样看起来和 to_xx 系列更和谐

考虑1下..

2017-09-11 06:51 UTC, liu-s-yuan commented on doc/acid/time.md
> +  - [time.us](#timeus)
嗷嗷，好

2017-09-11 06:56 UTC, liu-s-yuan commented on lib/acid/time.lua
> +
关于函数命名，我改一下。
get_time()的话，我是想同时得到秒，毫秒和微秒数，之后我写生成一个全局唯一的时间戳的时候会用到它

2017-09-11 06:58 UTC, wenbobuaa commented on lib/acid/time.lua
> +
嗷嗷

2017-09-11 10:42 UTC, drmingdrmer approved these changes

2017-09-12 07:07 UTC, pengsven approved these changes

2017-09-12 08:23 UTC, wenbobuaa approved these changes

2017-09-12 08:37 UTC, merged