给strutil的几个函数添加了文档
baishancloud/lua-acid pull request #58
Opened 2017-10-12 03:33 UTC by liu-s-yuan

* add doc for right_n_split()

* add doc for fnmatch()

* add doc for to_chunks()

* delete replace()

2017-10-12 03:43 UTC, drmingdrmer requested changes
参考测试用例来写文档.测试里能体现出所有的feature和行为.

2017-10-12 03:43 UTC, drmingdrmer commented on doc/acid/strutil.md
> +Convert escape chars and special chars in `ptn` to chars that Lua can recognize.
这句不是他主要功能. 参考下python的fnmatch的描述.

2017-10-12 03:43 UTC, drmingdrmer commented on doc/acid/strutil.md
> +    It must be greater than 0.
说明是可以是小数, 和是小数时的行为.

2017-10-12 03:47 UTC, liu-s-yuan commented on doc/acid/strutil.md
> +Convert escape chars and special chars in `ptn` to chars that Lua can recognize.
嗷嗷，我去看一下

2017-10-12 03:47 UTC, liu-s-yuan commented on doc/acid/strutil.md
> +    It must be greater than 0.
嗷嗷，好的

2017-10-12 03:51 UTC, wenbobuaa commented on doc/acid/strutil.md
> +  - [strutil.fnmatch](#strutilfnmatch)
这个的顺序..应该在上面

2017-10-18 06:26 UTC, drmingdrmer approved these changes

2017-10-18 06:37 UTC, wenbobuaa approved these changes

2017-10-18 08:23 UTC, pengsven approved these changes

2017-10-18 08:31 UTC, merged