添加生成和解析一个全局唯一的ID
baishancloud/lua-acid pull request #59
Opened 2017-10-12 07:54 UTC by liu-s-yuan

* add guid.generate() to generate a unique id

* add guid.parse() to parse a unique id

* add typeutil for type checking of guid arguments

2017-10-12 11:05 UTC, pengsven commented on lib/acid/guid.lua
> +        end
这个判断和下面的sleep时间不一致

2017-10-12 11:05 UTC, pengsven commented on doc/acid/guid.md
> +    it is a positive integer and it can not be more than 13.
解释1下为啥不能超过13

2017-10-12 11:05 UTC, pengsven commented on doc/acid/guid.md
> +    it is a positive integer.
和实现有些差异，描述1下取值范围

2017-10-12 11:05 UTC, pengsven commented on doc/acid/guid.md
> +    it is a positive integer.
同上

2017-10-12 11:05 UTC, pengsven commented on lib/acid/typeutil.lua
> +    return true
15-19行简化1下

2017-10-12 12:36 UTC, pengsven approved these changes

2017-10-13 05:07 UTC, drmingdrmer requested changes
先推个typeutil的pr. 如果没有特殊情况, 如果包含没测试的代码不要提pr.

2017-10-18 09:30 UTC, drmingdrmer approved these changes
几个文档和小优化的建议, 酌情采纳.

2017-10-18 09:30 UTC, drmingdrmer commented on doc/acid/guid.md
> +    is max wait time of making a guid.
is the max wait time to make a guid

2017-10-18 09:30 UTC, drmingdrmer commented on doc/acid/guid.md
> +    timestamp can be accurate to milliseconds.
timestamp provides millisecond level accuracy, 酱?

2017-10-18 09:30 UTC, drmingdrmer commented on doc/acid/guid.md
> +    It is an integer and it must be greater than or equal to 1.
需要解释下什么是`seq`

2017-10-18 09:30 UTC, drmingdrmer commented on doc/acid/guid.md
> +It provides generating and parsing a unique id.
解释下guid的格式..

2017-10-18 09:30 UTC, drmingdrmer commented on lib/acid/guid.lua
> +local function next_req(self, timestamp)
next_req里的req是啥?

2017-10-18 09:30 UTC, drmingdrmer commented on lib/acid/guid.lua
> +    local guid_tb = ngx.re.match(guid, string.format(
pattern可以在构造函数里生成吧? 貌似都是确定的.

2017-10-18 09:31 UTC, liu-s-yuan commented on doc/acid/guid.md
> +It provides generating and parsing a unique id.
嗷嗷，好

2017-10-18 09:32 UTC, liu-s-yuan commented on doc/acid/guid.md
> +    It is an integer and it must be greater than or equal to 1.
嗷嗷，好

2017-10-18 09:36 UTC, liu-s-yuan commented on lib/acid/guid.lua
> +local function next_req(self, timestamp)
这里应该是seq，我去改了

2017-10-18 12:37 UTC, drmingdrmer commented on doc/acid/guid.md
> +    `seq` is the number of generating guid in the current timestamp.
seq is a monotonically incremental integer as the second significant part of a guid to avoid duplication on a single machine. 酱婶?

2017-10-18 12:37 UTC, drmingdrmer commented on doc/acid/guid.md
> +    It is an integer and it must be greater than or equal to 1.
解释下mid的用途. 可以试试 translate.google.com ..

2017-10-18 12:37 UTC, drmingdrmer commented on lib/acid/guid.lua
> +local function next_req(self, timestamp)
这是啥啊...

2017-10-18 12:38 UTC, drmingdrmer requested changes
...

2017-10-19 11:27 UTC, drmingdrmer approved these changes

2017-10-19 11:50 UTC, merged