添加了两个类型检查的函数
baishancloud/lua-acid pull request #60
Opened 2017-10-13 07:02 UTC by liu-s-yuan

1.添加检查数字范围的函数
2.添加了检查数字是否为整数的函数

2017-10-13 07:10 UTC, drmingdrmer requested changes
顺手填上文档吧. 完整的pr.

2017-10-13 07:10 UTC, drmingdrmer commented on lib/acid/typeutil.lua
> +function _M.check_number_range(val, min, max)
加参数指定 min, max是open的还是closed: 是否允许值等于min或max. 确定默认情况是open还是closed.

可以考虑加个int_range的检查,因为整数简单点, 不需要open/closed. 实数需要.

2017-10-13 07:14 UTC, liu-s-yuan commented on lib/acid/typeutil.lua
> +function _M.check_number_range(val, min, max)
嗷嗷，我去想一下

2017-10-16 03:16 UTC, pengsven approved these changes

2017-10-16 03:16 UTC, pengsven commented on lib/acid/typeutil.lua
> +    end
min = min or -INF和if left_closed == nil then left_closed = true end两种写法有啥区别？

2017-10-16 03:17 UTC, wenbobuaa approved these changes

2017-10-16 03:20 UTC, liu-s-yuan commented on lib/acid/typeutil.lua
> +    end
如果写成left_closed = left_closed or true的话，left_closed为false的时候，结果也会是true，所以不能写成这样

2017-10-16 03:22 UTC, wenbobuaa commented on lib/acid/typeutil.lua
> +    end
left_closed 指的是区间的开闭吧

2017-10-16 03:24 UTC, liu-s-yuan commented on lib/acid/typeutil.lua
> +    end
对，left_closed指的是区间左侧的开闭

2017-10-16 03:24 UTC, drmingdrmer requested changes

2017-10-16 03:24 UTC, drmingdrmer commented on doc/acid/typeutil.md
> +    is the minimum of the range.
注明包含这个min还是不包含这个min

2017-10-16 03:24 UTC, drmingdrmer commented on lib/acid/typeutil.lua
> +    end
这几行判断逻辑不清楚.整理下.

2017-10-16 03:24 UTC, drmingdrmer commented on lib/test_typeutil.lua
> +        {'2',   0, 1, false },
int的string不是int. check_int_range里调用的is_int应该是只有int才返回true. 否则is_int的行为就跟描述不符.

2017-10-16 03:25 UTC, liu-s-yuan commented on lib/test_typeutil.lua
> +        {'2',   0, 1, false },
嗷嗷，好的

2017-10-16 03:25 UTC, liu-s-yuan commented on lib/acid/typeutil.lua
> +    end
好，我去整理下

2017-10-16 03:26 UTC, liu-s-yuan commented on doc/acid/typeutil.md
> +    is the minimum of the range.
嗷嗷，好的

2017-10-16 07:46 UTC, drmingdrmer requested changes

2017-10-16 07:46 UTC, drmingdrmer commented on lib/acid/typeutil.lua
> +        end
min用1个if, max用1个if.不要把这2个混到1起. 会清楚1点.

2017-10-16 07:48 UTC, liu-s-yuan commented on lib/acid/typeutil.lua
> +        end
嗷嗷，好的

2017-10-16 08:48 UTC, drmingdrmer commented on lib/acid/typeutil.lua
> +            return true
逻辑不对

2017-10-16 08:50 UTC, liu-s-yuan commented on lib/acid/typeutil.lua
> +            return true
恩？不会啊，测试是通过的啊

2017-10-17 03:44 UTC, drmingdrmer requested changes

2017-10-17 03:44 UTC, drmingdrmer commented on doc/acid/typeutil.md
> +The range is closed.
The range is closed. It means `val` can be `min` or `max`. Unlike `check_number_range()`, in which a user is able to specify whether left/right boundary is closed or opened.

2017-10-17 03:44 UTC, drmingdrmer commented on lib/acid/typeutil.lua
> +    if _M.is_int(val) and _M.check_number_range(val, min, max) then
内部模块的调用强制下left/right closed的参数吧, 能明确的地方就明确1下.

2017-10-17 03:44 UTC, drmingdrmer commented on lib/test_typeutil.lua
> +        {'0',   0,   1,   nil,   nil,   true,  'range = [0, 1]'      },
可以转化成number的string还是不是number的. 或者另外起个函数, 或者加个参数指定是否允许number-string.

2017-10-17 03:44 UTC, drmingdrmer commented on lib/test_typeutil.lua
> +        {'abc', 0,   1,   nil,   nil,   false, 'range = [0, 1]'      },
测试table, function等类型的输入.

2017-10-17 03:47 UTC, liu-s-yuan commented on lib/acid/typeutil.lua
> +    if _M.is_int(val) and _M.check_number_range(val, min, max) then
嗷嗷，好的

2017-10-17 03:47 UTC, liu-s-yuan commented on lib/test_typeutil.lua
> +        {'abc', 0,   1,   nil,   nil,   false, 'range = [0, 1]'      },
嗷嗷，好

2017-10-17 03:48 UTC, liu-s-yuan commented on lib/test_typeutil.lua
> +        {'0',   0,   1,   nil,   nil,   true,  'range = [0, 1]'      },
我去想一下

2017-10-17 08:18 UTC, drmingdrmer approved these changes

2017-10-17 08:18 UTC, drmingdrmer commented on doc/acid/typeutil.md
> +Same as `typeutil.check_number_range` except the `val` is a number string.
这里说明`val`可以是number也可以是能解析成number的string吧. 允许它接受1个数字, 这样好点不?

2017-10-17 08:23 UTC, liu-s-yuan commented on doc/acid/typeutil.md
> +Same as `typeutil.check_number_range` except the `val` is a number string.
那这里的函数名还继续使用check_number_string_range() 吗，

2017-10-17 11:16 UTC, drmingdrmer commented on doc/acid/typeutil.md
> +Same as `typeutil.check_number_range` except the `val` is a number string.
看你需要额..

2017-10-17 12:12 UTC, pengsven approved these changes

2017-10-17 12:12 UTC, pengsven commented on lib/acid/typeutil.lua
> +    if val < min or val == min and not left_closed then
x1 or x2 and x3的方式用 x1 or (x2 and x3)的方式更易于阅读些

2017-10-17 12:12 UTC, pengsven commented on doc/acid/typeutil.md
> +Same as `typeutil.check_number_range` except the `val` is a number string.
感觉可

2017-10-17 12:12 UTC, pengsven commented on lib/acid/typeutil.lua
> +    return _M.check_number_range(tonumber(val), min, max, left_closed, right_closed)
这里tonumber一次吧

2017-10-17 12:20 UTC, drmingdrmer approved these changes

2017-10-18 03:11 UTC, merged