使用数组存放callback
baishancloud/lua-acid pull request #70
Opened 2017-11-07 02:18 UTC by 13yu

1，ngx.ctx.callback_functions -> ngx.ctx.callbacks
2, ngx.ctx.callbacks 从字典类型改为数组
3，添加add_callback_with_opts函数，支持设置某个callback始终位于数组的末尾，支持指定插入到任意位置。
4，t/ngx_abort.t  -> t/ngx_abort_test.t
5, 添加测试lib/test_ngx_abort.lua

2017-11-07 06:04 UTC, drmingdrmer requested changes

2017-11-07 06:04 UTC, drmingdrmer commented on lib/acid/ngx_abort.lua
> +function _M.add_callback(func, ...)
这个函数为啥不调用`add_callback_with_opts`来实现?..

2017-11-07 06:04 UTC, drmingdrmer commented on lib/acid/ngx_abort.lua
> +        cb.func(unpack(cb.args))
不太记得了..lua里的ipairs可以遍历出离散的 list形式的table的所有index吗? `{1=1, 5=5}` 这种table

2017-11-07 06:28 UTC, 13yu commented on lib/acid/ngx_abort.lua
> +        cb.func(unpack(cb.args))
确实不行，我改成pairs吧

2017-11-07 06:32 UTC, 13yu commented on lib/acid/ngx_abort.lua
> +function _M.add_callback(func, ...)
嗯，我改下

2017-11-07 07:55 UTC, pengsven commented on lib/acid/ngx_abort.lua
> +        return cb, nil, nil
这会覆盖之前已经设置last的cb

2017-11-07 07:55 UTC, pengsven commented on lib/acid/ngx_abort.lua
> +    end
指定位置add个cb好像意义不大

2017-11-07 08:08 UTC, 13yu commented on lib/acid/ngx_abort.lua
> +        return cb, nil, nil
这里允许有多个设置为last的cb，不过可以保证他们都集中在尾部

2017-11-07 08:08 UTC, 13yu commented on lib/acid/ngx_abort.lua
> +    end
嗯

2017-11-07 09:49 UTC, drmingdrmer commented on lib/acid/ngx_abort.lua
> +    end
有些吧...比如有好几组cb, 每组有多个cb, 这样可以指定每个cb插入时使用100, 200,300,来确定每组之间的顺序,和忽略组内的顺序.

2017-11-07 09:51 UTC, drmingdrmer commented on lib/acid/ngx_abort.lua
> +        cb.func(unpack(cb.args))
pair出来需要sort...

2017-11-07 10:41 UTC, 13yu commented on lib/acid/ngx_abort.lua
> +        cb.func(unpack(cb.args))
哦，对

2017-11-08 05:33 UTC, drmingdrmer requested changes

2017-11-08 05:33 UTC, drmingdrmer commented on lib/acid/ngx_abort.lua
> +        if callbacks[empty_index] == nil then
感觉有点麻烦了.. callbacks里的每个元素做成数组吧. 如果要表示最后1个必须最后运行的话, callbacks里设定成`{1={cb1,cb2..} ,2=...,5..., last={cbx,cby}}`来区分indexed 和设置为last的.

2017-11-08 16:23 UTC, drmingdrmer approved these changes

2017-11-22 03:07 UTC, drmingdrmer approved these changes

2017-11-22 03:07 UTC, drmingdrmer commented on lib/acid/ngx_abort.lua
> +local function comp(a, b)
local的加下划线标识下: `_comp`, 名字太简单了..可以描述下比较的是啥, 譬如 `_cmp_callback_index`啥的.

2017-11-22 03:10 UTC, 13yu commented on lib/acid/ngx_abort.lua
>      end
如果指定的插入位置已经存放了callback，就往后找一个没有存放callback的index存放

2017-11-22 03:10 UTC, 13yu commented on lib/acid/ngx_abort.lua
> +    for _, cb in ipairs(postpone_cbs) do
不再使用位置区分设置为last的callback， 再执行callbacks时，先挑选出来，然后单独执行

2017-11-22 03:10 UTC, 13yu commented on lib/acid/ngx_abort.lua
> +        if callbacks[empty_index] == nil then
嗯，有道理

2017-11-22 03:10 UTC, 13yu commented on lib/acid/ngx_abort.lua
> +local function comp(a, b)
好，我改下

2017-11-22 06:56 UTC, closed without merging