tableutil add add and addto
baishancloud/lua-acid pull request #73
Opened 2017-11-18 03:18 UTC by tongwei

2017-11-18 07:12 UTC, drmingdrmer requested changes
代码,测试,文档,这3部分一起提交.

2017-11-18 07:12 UTC, drmingdrmer commented on lib/acid/tableutil.lua
> +        opts.recursive = false
不应该修改通过引用方式传进来的参数

2017-11-18 07:12 UTC, drmingdrmer commented on lib/acid/tableutil.lua
> +                    if opts.default then
显式地判断default是什么, 不要用单个变量做为bool使用. 容易有坑.

2017-11-18 07:12 UTC, drmingdrmer commented on lib/acid/tableutil.lua
> +                if a[k] == nil then
上面这几个if判断感觉不太清楚. 整理下.看有没清楚的表达方式. 

a,b两个table如果类型不一样怎么处理?

2017-11-18 07:37 UTC, 13yu commented on lib/acid/tableutil.lua
应该也需要乘法操作，是不是可以添加一个参数指定操作类型

2017-11-20 02:17 UTC, 13yu commented on lib/acid/tableutil.lua
对了，实际使用的时候，table里可能还会包含一些不需要累加的key，可不可提供一个可选参数例如（exclusive_keys）传入不需要累加的key

2017-11-20 05:26 UTC, tongwei commented on lib/acid/tableutil.lua
这个exclusive_keys感觉不是特别需要，如果忽略的key特别多的话。

2017-11-20 05:44 UTC, 13yu commented on lib/acid/tableutil.lua
不会很多，如果没有忽略功能的话，上层逻辑可能需要做一些额外的操作

2017-11-20 09:07 UTC, 13yu commented on lib/acid/tableutil.lua
> +                if a[k] == nil and opts.default ~= nil and type(v) == 'number' then
如果type（v）== ‘table’，应该也需要combine到a

2017-11-20 09:10 UTC, 13yu commented on doc/acid/tableutil.md
> +`tableutil.combine(a, b, opts, operator)`
这个operator 可以提供一个默认函数吧，不然上层代码每次都要自己创建一个函数，会麻烦一点

2017-11-20 09:35 UTC, tongwei commented on lib/acid/tableutil.lua
> +                if a[k] == nil and opts.default ~= nil and type(v) == 'number' then
opts.default是个数字和table v咋合在一起啊

2017-11-20 09:37 UTC, tongwei commented on doc/acid/tableutil.md
> +`tableutil.combine(a, b, opts, operator)`
这个我再想想。

2017-11-20 09:56 UTC, 13yu commented on lib/acid/tableutil.lua
> +                if a[k] == nil and opts.default ~= nil and type(v) == 'number' then
a={}, b={foo={trffic_up=100}}, 合并后 a={foo={traffic_up=100}}, 这样，a[k]为nil， v为table的时候， default值可以作用于v里面的每个key

2017-11-20 10:48 UTC, drmingdrmer requested changes

2017-11-20 10:48 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +`tableutil.combineto(a, b, opts, operator)`
opts放最后. 作为可选参数.

2017-11-20 10:48 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +If `opts.default` is a number value, key not existed in a but in a has a default value.
a加反引号. 和冠词a区分开

2017-11-20 10:48 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +If `opts.exclusive_keys` is not nil, the key in exclusive_keys will be ignored.
`exclude_keys`

2017-11-20 10:48 UTC, drmingdrmer commented on lib/acid/tableutil.lua
>  end
留个addto和add的函数吧,方便使用.每次都传operator很麻烦额

2017-11-20 10:57 UTC, tongwei commented on lib/acid/tableutil.lua
> +                if a[k] == nil and opts.default ~= nil and type(v) == 'number' then
这个逻辑和之前addto逻辑不太一样哈，a={}, b={foo={trffic_up=100}}这种情况有default值得话，应该是合并不起来的，因为数字和table没办法相加，结果只能是{}；如果没有设置default的话，a中的值就会比忽略了。

2017-11-20 11:11 UTC, 13yu commented on lib/acid/tableutil.lua
> +                if a[k] == nil and opts.default ~= nil and type(v) == 'number' then
在a[k]为nil， v为table的时候， 先设置a[k] = {}, 然后再_combine_internal(a[k], v, opts, copy_return, operator, key_prefix)感觉应该可以吧

2017-11-20 11:39 UTC, tongwei commented on lib/acid/tableutil.lua
> +                if a[k] == nil and opts.default ~= nil and type(v) == 'number' then
感觉是和opts.default参数的定义有些冲突，@drmingdrmer 咋看？

2017-11-21 03:16 UTC, drmingdrmer requested changes

2017-11-21 03:16 UTC, drmingdrmer commented on lib/acid/tableutil.lua
> +    local opts = opts or {}
用if来判断是否是nil来设置默认值. 习惯了这种or的写法容易出现opts是false的那个bug.

2017-11-21 03:16 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +    See more details about **key_path** at [tableutil.contains](#tableutilcontains).
确认下你对contains的理解是正确的..然后..感觉`exclude_keys` 直接用1个深度的table来标识排除比较好. 为啥要转成字符串呢?

2017-11-21 04:41 UTC, tongwei commented on doc/acid/tableutil.md
> +    See more details about **key_path** at [tableutil.contains](#tableutilcontains).
感觉{'x.y.z'}这种写法比{{'x','y','z'}}这种写法更直观些。

2017-11-21 06:16 UTC, tongwei commented on doc/acid/tableutil.md
> +    See more details about **key_path** at [tableutil.contains](#tableutilcontains).
contains是指任稚说的那个吗？

2017-11-21 11:30 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +    See more details about **key_path** at [tableutil.contains](#tableutilcontains).
我是说..`{'x.y.z'} --> {x={y={z=1}}}` 酱.

任稚说了啥?...

2017-11-22 03:04 UTC, drmingdrmer reviewed
几个小问题.

2017-11-22 03:04 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +It is a alias as `tableutil.combine(a,b,function(a, b) return a + b end,opts)`
前后两组变量都是a和b,重复了.区分下. 写文档和代码都一样, 第一原则是表意清晰.

2017-11-22 03:04 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +If `opts.recursive` is true, we do combineto recursively.
代码的常量true, 用反引号括起来.

2017-11-22 03:04 UTC, drmingdrmer commented on doc/acid/tableutil.md
> +local opts = {opts.exclude_keys={x={z=true}}}
如果是字典的话exclude_keys这个名字就不合适了.

2017-11-22 03:04 UTC, drmingdrmer commented on lib/test_tableutil.lua
> +        {opts_default,			{x=1,y=2,z=3},			{x=1,y=2,z=3},			{x=2,y=4,z=6}},
有点没对齐`@_@`...

2017-11-22 03:10 UTC, drmingdrmer approved these changes

2017-11-22 03:29 UTC, 13yu approved these changes

2017-11-22 03:29 UTC, 13yu commented on lib/acid/tableutil.lua
> +                        rst[k] = _combine_internal({}, v, opts, copy_return, operator, sub_exclude_keys)
太长了，可以换下行

2017-11-22 05:59 UTC, merged