urlutil add normalize_uri
baishancloud/lua-acid pull request #79
Opened 2017-12-26 11:57 UTC by tongwei

2017-12-27 02:45 UTC, drmingdrmer requested changes

2017-12-27 02:45 UTC, drmingdrmer commented on doc/acid/urlutil.md
> +##  urlutil.url-escape
不要用减号.标题保持和代码一直.

2017-12-27 02:45 UTC, drmingdrmer commented on lib/acid/urlutil.lua
> +    local path_query = strutil.split(uri, '?', {maxsplit=1})
opts里需要强制用plain参数

2017-12-27 02:45 UTC, drmingdrmer commented on lib/acid/urlutil.lua
> +    local segments = strutil.split(path_query[1], '/')
看下split的文档. 必须强制plain模式.

2018-01-02 07:29 UTC, pengsven commented on lib/acid/urlutil.lua
> +    end
139 ~141 和 143的(query or '') 整合在一起

2018-01-10 03:50 UTC, drmingdrmer commented on lib/acid/urlutil.lua
> +    end
@tongwei 这个还没修改?

2018-01-10 08:22 UTC, tongwei commented on lib/acid/urlutil.lua
> +    end
改了啊

2018-01-12 05:23 UTC, drmingdrmer approved these changes

2018-01-12 05:23 UTC, drmingdrmer commented on lib/acid/urlutil.lua
> +    if query == nil then
这里用else更清楚一点

2018-02-06 11:35 UTC, pengsven approved these changes

2018-02-06 11:44 UTC, merged