add serialize_hash
baishancloud/lua-acid pull request #89
Opened 2018-03-05 06:31 UTC by tongwei

2018-03-05 11:36 UTC, pengsven commented on lib/test_serialize_hash.lua
> +    local data = ''
测试用例尽量覆盖全写

2018-03-05 11:36 UTC, pengsven commented on lib/acid/serialize_hash.lua
> +    local schema = schemas[mode]
这里需要判断1下schema==nil的情况，deserialize函数也是

2018-03-05 11:36 UTC, pengsven commented on lib/acid/serialize_hash.lua
> +return _M
去掉行尾非法字符

2018-03-06 10:50 UTC, drmingdrmer requested changes
命名和接口不太清楚. @pengsven 帮 @tongwei 先优化下接口的定义. 给使用者最直接的定义.

2018-03-06 10:50 UTC, drmingdrmer commented on doc/acid/serialize_hash.md
> +`ctx, err, errmsg = serialize_hash.serialize(alg_obj, mode)`
文档写的不清楚, alg_obj是什么, ctx是什么, 这些..`hash object`是什么鬼... 名字是alg_obj, 解释是hash object

2018-03-06 10:50 UTC, drmingdrmer commented on lib/acid/serialize_hash.lua
> +function _M.serialize(alg_obj, mode)
输入为什么是一个alg_obj? 只用到里面的_ctx字段了.

接口不是最简单的形式. 简化一下.

返回的也是ctx, 和输入的有什么区别? 是同样的东西吗?

尽量避免context, object, 这类没有具体含义的名词做变量名. 用它实际的内容/含义命名.

2018-03-15 07:59 UTC, pengsven requested changes

2018-03-15 07:59 UTC, pengsven commented on doc/acid/serialize_hash.md
> +acid.serialize_hash
serialize_hash命令有些长，叫hashlib如何？

2018-03-15 07:59 UTC, pengsven commented on doc/acid/serialize_hash.md
> +`cdata_ctx, err, errmsg = serialize_hash.deserialize(ctx, mode)`
第二个参数直接用algorithm吧

2018-03-15 07:59 UTC, pengsven commented on lib/acid/serialize_hash.lua
> +                data = function(val) return ffiutil.tbl_to_carray('unsigned long[16]', val, str_to_unsiged_clong) end,
'unsigned long[16]' 这里直接用 MD5_LONG data[MD5_LBLOCK]， 和md5.lua里保持一致

2018-03-15 07:59 UTC, pengsven commented on lib/acid/serialize_hash.lua
> +                data = function(val) return ffiutil.carray_to_tbl(val, 16, clong_to_str) end,
这里的16 也是应用c.enum.MD5_LBLOCK

2018-03-15 07:59 UTC, pengsven commented on lib/acid/serialize_hash.lua
> +    local cdata_ctx, err, errmsg = ffiutil.tbl_to_cdata(ctype, ctx, enc_schema)
107~114 直接return  ffiutil.tbl_to_cdata(ctype, ctx, enc_schema) 就可以了

2018-03-15 07:59 UTC, pengsven commented on lib/acid/serialize_hash.lua
> +    local ctx, err, errmsg = ffiutil.cdata_to_tbl(cdata_ctx, dec_schema)
同上

2018-03-15 07:59 UTC, pengsven commented on lib/acid/serialize_hash.lua
> +        return nil, 'UnsupportedMode', string.format('%s is unsupported',mode)
UnsupportedMode 建议改成UnsupportedAlgorithm， errmsg里描述支持的algorithm和参数的algorithm

2018-03-15 07:59 UTC, pengsven commented on lib/test_serialize_hash.lua
> +    local cases = {
测试用例设计的有些简单，考虑下各种情况

2018-03-16 14:57 UTC, drmingdrmer requested changes

2018-03-16 14:57 UTC, drmingdrmer commented on doc/acid/hashlib.md
> +Utility functions for hash lib.
文档需要加个synopsis展示基本用法.

描述里需要加上为什么要设计这个模块.

文档和代码的目的是传达设计思想, 把自己知道的东西都用代码/文档表达出来.

2018-03-19 06:13 UTC, drmingdrmer approved these changes

2018-03-19 06:42 UTC, tongwei commented
@drmingdrmer @pengsven ,根据义谱建议，添加update、reset、final包装，去掉serialize& deserialize不必要参数，帮忙再看看哈

2018-03-19 08:12 UTC, pengsven approved these changes

2018-03-19 08:12 UTC, pengsven commented
done

2018-03-19 08:21 UTC, drmingdrmer approved these changes

2018-03-19 09:05 UTC, merged