ffiutil add bad schema and nil check
baishancloud/lua-acid pull request #90
Opened 2018-03-07 07:56 UTC by tongwei

2018-03-07 08:07 UTC, drmingdrmer requested changes

2018-03-07 08:07 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +    for k, v in tableutil.iter(schema) do
为啥不用pairs? 这里如果有原因的话需要注释说明1下. 代码上看不出为啥不用pairs.

2018-03-07 08:07 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +    return err, ...
别用这种技巧...让代码难读.直接接受pcall的返回.然后if.

2018-03-07 08:07 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +                return nil, 'Nil', ' is nil'
Nil 这个错误码太简单了. 错误码让人能看懂最好.

2018-03-07 08:36 UTC, tongwei commented on lib/acid/ffiutil.lua
> +    for k, v in tableutil.iter(schema) do
hao

2018-03-07 08:36 UTC, tongwei commented on lib/acid/ffiutil.lua
> +    return err, ...
hao

2018-03-07 08:36 UTC, tongwei commented on lib/acid/ffiutil.lua
> +                return nil, 'Nil', ' is nil'
hao

2018-03-07 08:41 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +    -- use iter to keep the conversion order of schema
这里为啥要保持顺序? 没看出来有啥必要

2018-03-07 08:44 UTC, tongwei commented on lib/acid/ffiutil.lua
> +    -- use iter to keep the conversion order of schema
保证每次解析错误的时候报错一样。这样测试好写点，报错的时候也好查。

2018-03-07 08:45 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
>              if new_tbl == nil then
为什么只有type v是table和function的时候new_tbl才不能是nil? new_tbl 好像什么时候都不能是nil吧? 

逻辑不太清楚, 这段代码重新考虑用更清楚的方法来表达.

写代码是优先表达清楚. 然后才考虑实现功能.

2018-03-07 08:46 UTC, drmingdrmer requested changes

2018-03-07 08:46 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +                return nil, 'MissingValue', ' is nil'
MissingValue是什么意思?

2018-03-07 09:10 UTC, tongwei commented on lib/acid/ffiutil.lua
> +                return nil, 'MissingValue', ' is nil'
值缺失。我换成NilValue吧

2018-03-07 09:11 UTC, tongwei commented on lib/acid/ffiutil.lua
>              if new_tbl == nil then
嗯，写的时候没想太清楚

2018-03-08 05:56 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +                return nil, 'MissingValue', ' is nil'
什么值确实? new_tbl是nil为啥是值确实?感觉逻辑和命名有点对不上?

2018-03-08 05:58 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +    -- use iter to keep the conversion order of schema
这些代码上不能直接反应出来的设计意图, 需要用注释来说明了.

2018-03-08 06:22 UTC, tongwei commented on lib/acid/ffiutil.lua
> +                return nil, 'MissingValue', ' is nil'
本意是想表达这个字段是nil，缺少值。后来感觉直接说值是Nil好一点

2018-03-08 06:56 UTC, drmingdrmer requested changes

2018-03-08 06:56 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +        return nil, 'UnknowError', err_or_rst
unknown 少了最后的n.

2018-03-08 06:56 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +            return nil, 'NilValue', string.format('%s is nil', k)
这里感觉用python那套错误定义挺好的: KeyError, 表示查询key的时候失败.

error message里描述清楚, 光`xxx is nil`看不出来是什么问题. `schema required key "xxx" not in 'tbl'` 酱写. 场景, 错误原因, 出错的对象是啥, 可以的话尽量包含这3个信息.

2018-03-08 06:56 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
>                  return nil, err, string.format('%s.%s', k, errmsg)
错误信息有点草率.

2018-03-08 06:56 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
>      local new_tbl = tableutil.dup(tbl, true)
dup完全没有必要啊在这里. 转换每个key-value之后复制到一个新的table不就行了吗?

2018-03-09 10:45 UTC, tongwei commented
依赖#91

2018-03-09 11:26 UTC, drmingdrmer requested changes
先修改tableutil. 在使用. 类似的功能其他地方也要用到. 基础库的代码规划时做好长期打算.

2018-03-09 11:26 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +local function _cdata_get(cdata, ks)
不加这个函数了. 需要用的话改下tableutil.get,让它支持table类型的keys是最好的吧?

2018-03-09 11:27 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +local function _cdata_get(cdata, ks)
额? 你已经改了tableutil? 那为啥没用它额?

2018-03-09 11:30 UTC, tongwei commented on lib/acid/ffiutil.lua
> +local function _cdata_get(cdata, ks)
cdata数据用tableutil获取感觉不太合适。

2018-03-09 11:33 UTC, drmingdrmer commented on lib/acid/ffiutil.lua
> +local function _cdata_get(cdata, ks)
为啥不适合?

2018-03-12 06:08 UTC, tongwei commented on lib/acid/ffiutil.lua
> +local function _cdata_get(cdata, ks)
cdata对象type不是table；如果访问不存在的字段的话也会直接报错，不会返回nil

2018-03-19 06:43 UTC, tongwei commented
@drmingdrmer @13yu ，这个有时间再看看哈

2018-03-19 07:39 UTC, 13yu approved these changes

2018-03-19 08:27 UTC, drmingdrmer approved these changes

2018-03-19 08:34 UTC, pengsven approved these changes

2018-03-19 08:34 UTC, pengsven commented on lib/acid/ffiutil.lua
> +    return err_or_rst, err, errmsg
return 返回3个值

2018-03-19 08:34 UTC, pengsven commented on lib/acid/ffiutil.lua
> +end
感觉保留_cdata_get就可以了

2018-03-19 08:52 UTC, tongwei commented on lib/acid/ffiutil.lua
> +end
保留_idx_lua_to_c感觉更清楚点

2018-03-19 09:01 UTC, merged