tableutil get set  key path table support
baishancloud/lua-acid pull request #91
Opened 2018-03-09 09:02 UTC by tongwei

2018-03-09 11:32 UTC, drmingdrmer commented on doc/acid/tableutil.md
>  the value `keys` access to if found in `tbl`. Or nil and error message.
这里也应该是key_path了吧?

2018-03-09 11:32 UTC, drmingdrmer commented on lib/test_tableutil.lua
> +    local two_level = gen_table_key_table(2, 1)
一共就2级...就至直接定义吧...不要引入别的函数了...代码越直接越好.

2018-03-09 11:32 UTC, drmingdrmer commented on lib/test_tableutil.lua
> +        local r, err, errmsg = tableutil.set(tbl, key_path, value, opts)
two_level在所有的case里都是同一个table的引用没问题吗?

2018-03-12 05:59 UTC, tongwei commented on lib/test_tableutil.lua
> +        local r, err, errmsg = tableutil.set(tbl, key_path, value, opts)
是有影响，这个测试用例的顺序没报错，我改下。

2018-03-12 06:00 UTC, tongwei commented on lib/test_tableutil.lua
> +    local two_level = gen_table_key_table(2, 1)
以table为key的table直接定义不太方便，下面set方法也能用到。

2018-03-12 07:09 UTC, drmingdrmer requested changes

2018-03-12 07:09 UTC, drmingdrmer commented on lib/test_tableutil.lua
> +    local two_level = gen_table_key_table(2, 1)
感觉直接定义没啥不方便的啊...

2018-03-12 07:22 UTC, tongwei commented on lib/test_tableutil.lua
> +    local two_level = gen_table_key_table(2, 1)
直接定义了。。

2018-03-12 07:38 UTC, drmingdrmer requested changes

2018-03-12 07:38 UTC, drmingdrmer commented on lib/test_tableutil.lua
> +    one_level[table_key] = 1
直接写1行不行吗...

2018-03-12 07:38 UTC, drmingdrmer commented on lib/test_tableutil.lua
> +    two_level[table_key] = tableutil.dup(one_level, true)
为啥要dup? 不能直接定义吗? 为啥整这么麻烦

2018-03-15 06:14 UTC, tongwei commented
@drmingdrmer , @13yu ,这个再给看看哈

2018-03-15 07:46 UTC, 13yu approved these changes

2018-03-15 07:46 UTC, 13yu commented on lib/acid/tableutil.lua
>          end
536行，'key path: %s.%s already exist', prefix, last_k ，last_k也用to_str(last_k)处理一下吧，这样比较一致。

2018-03-16 03:11 UTC, drmingdrmer approved these changes

2018-03-16 03:54 UTC, merged