add sql_constructor
baishancloud/lua-acid pull request #97
Opened 2018-03-21 03:14 UTC by 13yu

2018-03-21 03:32 UTC, drmingdrmer requested changes
先只看了readme部分, 每个sql-maker加个例子说明下生成的sql的样子. 对参数的解释除了格式说明也把作用说清楚.

2018-03-21 03:32 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +        m = 20,
感觉这个m没什么左右...mysql里好像`bigint(20)`里的20 只对显示有用. 对数据长度没有任何限制.

2018-03-21 03:32 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +Setup `backticked_name` and `select_expr` for each field.
一般这个不需要用户自己调用吧? 说明一下这点?

2018-03-21 03:32 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +    -   `set_field`:
`set_field`里的set是啥意思?

2018-03-21 03:32 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +        a lua table used to specify fields that contain range value,
只说明了格式,没有说作用啊..range有啥用?

2018-03-21 03:32 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +    -   `match`:
match放opts里咋样?

2018-03-21 03:32 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +        a lua table used to specify fields that are used to dentify rows
`dentify --> identify`

2018-03-21 03:38 UTC, 13yu commented on doc/acid/sql_constructor.md
> +        m = 20,
这个是用来验证输入参数长度的，这个模块了应该用不到，我把这个去掉

2018-03-21 03:42 UTC, 13yu commented on doc/acid/sql_constructor.md
> +Setup `backticked_name` and `select_expr` for each field.
需要用户在调用new之前调用这个函数，初始化一下这两个字段backticked_name， select_expr

2018-03-21 03:43 UTC, 13yu commented on doc/acid/sql_constructor.md
> +    -   `set_field`:
需要设置值的那些字段？

2018-03-21 03:44 UTC, 13yu commented on doc/acid/sql_constructor.md
> +        a lua table used to specify fields that contain range value,
我补充一下

2018-03-21 03:44 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +        m = 20,
它只能很粗略的验证, 没有什么用吧...

2018-03-21 03:46 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +Setup `backticked_name` and `select_expr` for each field.
为啥不在new里直接给做了?

2018-03-21 03:47 UTC, 13yu commented on doc/acid/sql_constructor.md
> +    -   `match`:
可以

2018-03-21 03:49 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +    -   `set_field`:
我看你后面用的是`allowed_param` 这个名词. 统一下吧, `allowed_field`? 后面感觉也可以用`allowed_field`

2018-03-21 03:52 UTC, 13yu commented on doc/acid/sql_constructor.md
> +Setup `backticked_name` and `select_expr` for each field.
放在new里面的话，每调用一次new就会重做一次，不过应该也没有太大的性能消耗，我调整下

2018-03-21 03:55 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +        a lua table used to specify fields that are used to dentify rows
vim里可以`:set spell` 打开语法检查. `]s`跳到下一个语法错误.

2018-03-21 03:56 UTC, 13yu commented on doc/acid/sql_constructor.md
> +        m = 20,
那我去掉吧

2018-03-21 03:59 UTC, 13yu commented on doc/acid/sql_constructor.md
> +    -   `set_field`:
好的

2018-03-21 04:02 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +Setup `backticked_name` and `select_expr` for each field.
或者new里检查下是否有做? 我觉得setup这步, 让用户自己调用也可以, 但可以明确一点, 用户定义的fields必须通过`sql_constructor.make_fields(raw_fields)`来生成一个. 不改传入参数,生成个新的东西返回回来. 可以考虑加个metatable做标记是已经初始化过的, 酱?

2018-03-21 05:18 UTC, 13yu commented on doc/acid/sql_constructor.md
> +Setup `backticked_name` and `select_expr` for each field.
嗯，感觉第一种让用户调用的方式简单点

2018-03-21 06:06 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +Setup `backticked_name` and `select_expr` for each field.
ok.

2018-03-21 06:42 UTC, 13yu commented on doc/acid/sql_constructor.md
> +    -   `match`:
用户请求的时候只会传一个json编码的args，不会有opts参数，match本身就是在args里面的，如果这里放到opts里面，中间需要opts.match = args.match， opts.leftopen = args.leftopen 等

2018-03-21 12:23 UTC, drmingdrmer commented on doc/acid/sql_constructor.md
> +	age = {20, 30},
args里的左右开闭默认保持左闭右开吧.

2018-03-21 12:42 UTC, drmingdrmer commented
review 加 @wenbobuaa

2018-03-21 13:02 UTC, 13yu commented on doc/acid/sql_constructor.md
> +	age = {20, 30},
好的

2018-03-22 04:54 UTC, drmingdrmer approved these changes

2018-03-24 08:42 UTC, wenbobuaa approved these changes

2018-03-24 08:42 UTC, wenbobuaa commented on doc/acid/sql_constructor.md
> +},
236~250 这一段怎么突然都用 tab 缩进了？
还有后面 299、382两段...

2018-03-24 08:42 UTC, wenbobuaa commented on doc/acid/sql_constructor.md
> +        For example, if `match` in `args` has value `{a=100}`, then,
这里应该是 "`match` in `opts`" ?

2018-04-03 02:41 UTC, 13yu commented on doc/acid/sql_constructor.md
> +        For example, if `match` in `args` has value `{a=100}`, then,
对，我改下

2018-04-03 02:43 UTC, 13yu commented on doc/acid/sql_constructor.md
> +},
嗯，可能是因为是复制过来的，我替换一下

2018-04-03 03:56 UTC, drmingdrmer commented
@sejust  也看看吧.

2018-04-10 03:56 UTC, tongwei commented on doc/acid/sql_constructor.md
> +        a lua table used to specify fields value, so only rows that with
match 和 ident 用法上有什么区别吗

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +        return ndk.set_var.set_quote_sql_str(value)
ndk.set_var.set_quote_sql_str 声明为 local的 可以提升一下效率

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    return string.format('UNHEX("%s")', value)
string.format 也可以声明为 local， 就不用每次去查找table了。

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    local _ = field
这一行 有什么特别的作用吗？

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    return string.format('`%s`', field_name)
函数看上去有点不对啊。。。   `A` as `B` ?

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +function _M.quote_value(field, value)
这个函数 和 下边的  ```_M.make_insert_sql``` 应该不是一个作用域的吧？
一个是 module.  一个是 class. 我觉得可以稍微区分一下

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    for field_name, _ in pairs(param.allowed_field) do
allowed_field 这个字段是否考虑缺省呢？  每次都要填一遍有点多余啊。
缺省的话就是全部字段

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +        end
判断 err ～= nil 可以放到 if ... else ... 外表 这样更简洁一点点

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +        return  nil, 'InvalidArgument', 'no field to set'
return 和 nil 多了个空格

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    local greater_than = '>='
greater_than 不是大于的意思吗

2018-04-10 04:10 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    if range == nil then
range 支持  单边吗？  比如 [0, oo) ?

2018-04-10 04:45 UTC, 13yu commented on doc/acid/sql_constructor.md
> +        a lua table used to specify fields value, so only rows that with
如果是用与匹配表中的某些行，match和ident的作用的一样的，可以互换，不过用ident会方便一点，如果需要生成update test_table set a=1 where a=0这样的sql，就需要使用match，输入为{a=1, match={a=0}}

2018-04-10 04:48 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +        return ndk.set_var.set_quote_sql_str(value)
嗯，好的

2018-04-10 04:49 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    return string.format('UNHEX("%s")', value)
嗯

2018-04-10 04:49 UTC, tongwei approved these changes

2018-04-10 04:51 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    local _ = field
这样可以让luacheck不输出 unused argument 的警告

2018-04-10 04:58 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    return string.format('`%s`', field_name)
select `field_a`, `field_b` from ... , 不用’as'，这个函数的作用相当于加了反引号，不用加‘as'了

2018-04-10 04:59 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +function _M.quote_value(field, value)
这个函数在其他模块也用到了，所以没有定义成local的

2018-04-10 05:06 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    for field_name, _ in pairs(param.allowed_field) do
有些action里面，allowed_field是可以缺失的，比如remove， 可以只需要ident，这时不太好区分是不需要还是应该使用默认全部字段，不过设置的时候可以使用tableutil.keys(_M.fields),也不会太麻烦。

2018-04-10 05:07 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +        end
嗯，是的

2018-04-10 05:08 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +        return  nil, 'InvalidArgument', 'no field to set'
我改下

2018-04-10 05:18 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    local greater_than = '>='
嗯，我换一个命名吧

2018-04-10 05:18 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    if range == nil then
现在不支持，我调整一下吧，

2018-04-10 05:36 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    local _ = field
可以把不需要的参数去掉吧

2018-04-10 05:42 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    local _ = field
这一系列函数都是回调函数，是通过一个函数统一调用的，传的参数都是一样的，所以不太好区分对待

2018-04-10 07:30 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    local _ = field
函数定义为一个参数， 调用时可以传2个参数

2018-04-10 07:40 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    if range == nil then
用  {nil, 20} 可以支持 a<=20 这个where吧？

2018-04-10 07:45 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    if range == nil then
nil经过json编解码好像会被去掉吧，我改成{left=20, right=30}这种形式吧

2018-04-10 07:52 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    local _ = field
还真是这样，我去掉吧

2018-04-13 12:13 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    for field_name, _ in pairs(param.allowed_field) do
感觉还是允许缺失好一点，我改成默认是全部字段的方式了

2018-04-17 02:34 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    for field_name, _ in pairs(param.allowed_field) do
嗯👌

2018-04-17 02:35 UTC, sejust commented on lib/acid/sql_constructor.lua
> +    if range == nil then
a={nil, 10}
a[2] 应该可以取到10哦

2018-04-17 02:54 UTC, 13yu commented on lib/acid/sql_constructor.lua
> +    if range == nil then
嗯。我好像想错了，json编码不会去掉第一个nil， 我改一下

2018-04-25 03:03 UTC, merged